# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 09:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30)),
                ('group_members', models.IntegerField(default=1)),
                ('group_description', models.TextField(max_length=150)),
                ('group_image', models.ImageField(blank=True, null=True, upload_to='group_images/')),
                ('group_listofmembers', models.ManyToManyField(blank=True, null=True, related_name='mberships', to=settings.AUTH_USER_MODEL)),
                ('group_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mgroups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='group_album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictures', models.ImageField(upload_to='group_images/')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_group', to='campaigns.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='group_posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts', models.TextField()),
                ('post_title', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_posts', to='campaigns.Campaign')),
                ('post_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='group_posts_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('comment_for_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_for_post', to='campaigns.group_posts')),
                ('comment_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(max_length=30)),
                ('meeting_description', models.TextField(max_length=150)),
                ('meeting_date', models.DateField(default=datetime.datetime(2016, 2, 20, 1, 58, 36, 905101))),
                ('meeting_location', models.TextField(max_length=50)),
                ('meeting_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_owner', to='campaigns.Campaign')),
                ('who_is_coming', models.ManyToManyField(related_name='who_is_coming', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
